version: "2"
run:
  build-tags:
    - cap
    - filament

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - goconst
    - goprintffuncname
    - govet
    - ineffassign
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - nolintlint
          - staticcheck
          - noctx
          - goconst
          - unparam
        path: _test\.go
      - linters:
          - goconst
        path: pkg/util/ports/iana_ports.go
      - linters:
          - goconst
        path: pkg/event/flags.go
      - linters:
          - goconst
        path: pkg/filter/ql/functions/(.+)\.go
      - linters:
          - goconst
        path: pkg/filter/ql/parser.go
      - linters:
          - goconst
        path: pkg/filter/ql/function.go
      - linters:
          - goconst
        path: pkg/filter/fields/fields_windows.go
      - linters:
          - goconst
        path: cmd/fibratus/app/list/list.go
      - linters:
          - goconst
        path: cmd/fibratus/app/rules/list.go
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

