run:
  build-tags:
    - kcap
    - filament
  deadline: 10m
  skip-files:
    - pkg/pe/entropy.go

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - errcheck
    - goconst
    - golint
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
