# ========================== Filter rules ================================
# This filter group rules try to mimic the subset of the sysmon config template
# created by SwiftOnSecurity (https://github.com/SwiftOnSecurity/sysmon-config).
#
# All credits for digging the rule definitions go to the above author/contributors.
#
# Obviously, some events can't be directly translated from the corresponding
# sysmon expressions, since Fibratus doesn't support them yet. In the same way,
# some filter fields are still missing in Fibratus, so that sysmon rules were
# omitted.
#
# ======================= Process creation ================================
#
# All processes launched will be logged, except for what matches a rule below.
# It's best to be as specific as possible, to avoid user-mode executables imitating
# other process names to avoid logging, or if malware drops files in an existing directory.
#
- group: Windows userspace and common apps processes
  selector:
    type: CreateProcess
  enabled: true
  policy: exclude
  relation: or
  from-strings:
    - name: Windows error reporting/telemetry, WMI provider host
      def: ps.comm startswith
          (
            ' \"C:\\Windows\\system32\\wermgr.exe\\" \"-queuereporting_svc\" ',
            'C:\\Windows\\system32\\DllHost.exe /Processid',
            'C:\\Windows\\system32\\wbem\\wmiprvse.exe -Embedding',
            'C:\\Windows\\system32\\wbem\\wmiprvse.exe -secured -Embedding'
          )
    - name: Windows error reporting/telemetry, Search Indexer, Session Manager, Auto check utility
      def: ps.comm in
          (
            'C:\\Windows\\system32\\wermgr.exe -upload',
            'C:\\Windows\\system32\\SearchIndexer.exe /Embedding',
            'C:\\windows\\system32\\wermgr.exe -queuereporting',
            '\\??\\C:\\Windows\\system32\\autochk.exe *',
            '\\SystemRoot\\System32\\smss.exe',
            'C:\\Windows\\System32\\RuntimeBroker.exe -Embedding'
          )
    - name: Various Windows processes
      def: ps.exe in
          (
            'C:\\Program Files (x86)\\Common Files\\microsoft shared\\ink\\TabTip32.exe',
            'C:\\Windows\\System32\\TokenBrokerCookies.exe',
            'C:\\Windows\\System32\\plasrv.exe',
            'C:\\Windows\\System32\\wifitask.exe',
            'C:\\Windows\\system32\\CompatTelRunner.exe',
            'C:\\Windows\\system32\\PrintIsolationHost.exe',
            'C:\\Windows\\system32\\SppExtComObj.Exe',
            'C:\\Windows\\system32\\audiodg.exe',
            'C:\\Windows\\system32\\conhost.exe',
            'C:\\Windows\\system32\\mobsync.exe',
            'C:\\Windows\\system32\\musNotification.exe',
            'C:\\Windows\\system32\\musNotificationUx.exe',
            'C:\\Windows\\system32\\powercfg.exe',
            'C:\\Windows\\system32\\sndVol.exe',
            'C:\\Windows\\system32\\sppsvc.exe',
            'C:\\Windows\\system32\\wbem\\WmiApSrv.exe'
          )
            or
          ps.comm in
          (
            'C:\\WINDOWS\\system32\\devicecensus.exe UserCxt',
            'C:\\Windows\\System32\\usocoreworker.exe -Embedding'
          )
    - name: svchost
      def: ps.comm in {{ .Values.processes.comm.svchost | stringify }}
    - name: Microsoft edge
      def: ps.comm startswith '\"C:\\Program Files (x86)\\Microsoft\\Edge Dev\\Application\\msedge.exe\" --type='
    - name: Microsoft dotNet
      def: ps.comm startswith
          (
            'C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\ngen.exe',
            'C:\\WINDOWS\\Microsoft.NET\\Framework64\\v4.0.30319\\Ngen.exe'
          )
            or
          ps.exe in
          (
            'C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorsvw.exe',
            'C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\mscorsvw.exe',
            'C:\\Windows\\Microsoft.Net\\Framework64\\v3.0\\WPF\\PresentationFontCache.exe'
          )
    - name: Microsoft Office
      def: ps.exe in
          (
            'C:\\Program Files\\Microsoft Office\\Office16\\MSOSYNC.EXE',
            'C:\\Program Files (x86)\\Microsoft Office\\Office16\\MSOSYNC.EXE',
            'C:\\Program Files\\Common Files\\Microsoft Shared\\OfficeSoftwareProtectionPlatform\\OSPPSVC.EXE',
            'C:\\Program Files\\Microsoft Office\\Office16\\msoia.exe',
            'C:\\Program Files (x86)\\Microsoft Office\\root\\Office16\\officebackgroundtaskhandler.exe',
            'C:\\Program Files\\Common Files\\Microsoft Shared\\ClickToRun\\OfficeC2RClient.exe'
          )
    - name: Media Player
      def: ps.exe = 'C:\\Program Files\\Windows Media Player\\wmpnscfg.exe'
    - name: Google
      def: ps.comm in
          (
            '\"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe\\\" --type='
          )


# ======================= Network connection initiated ================================
#
# By default this configuration takes a very conservative approach to network logging,
# limited to only extremely high-signal events.
#
- group: Suspicious network-connecting binaries
  selector:
    type: Connect
  enabled: true
  policy: include
  relation: or
  from-strings:
    - name: Suspicious sources for network-connecting binaries
      def: ps.exe startswith
          (
            'C:\\Users',
            'C:\\Recycle',
            'C:\\ProgramData',
            'C:\\Windows\\Temp',
            '\\',
            'C:\\perflogs',
            'C:\\intel',
            'C:\\Windows\\fonts',
            'C:\\Windows\\system32\\config'
          )
    - name: Suspicious Windows tools network-connecting binaries
      def: ps.name in
          (
            'at.exe',
            'certutil.exe',
            'cmd.exe',
            'cmstp.exe',
            'cscript.exe',
            'driverquery.exe',
            'dsquery.exe',
            'hh.exe',
            'infDefaultInstall.exe',
            'java.exe',
            'javaw.exe',
            'javaws.exe',
            'mmc.exe',
            'msbuild.exe',
            'mshta.exe',
            'msiexec.exe',
            'nbtstat.exe',
            'net.exe',
            'net1.exe',
            'notepad.exe',
            'nslookup.exe',
            'powershell.exe',
            'qprocess.exe',
            'qwinsta.exe',
            'reg.exe',
            'regsvcs.exe',
            'regsvr32.exe',
            'rundll32.exe',
            'rwinsta.exe',
            'sc.exe',
            'schtasks.exe',
            'taskkill.exe',
            'tasklist.exe',
            'wmic.exe',
            'wscript.exe'
          )
    - name: Relevant 3rd Party Tools
      def: ps.name in
          (
            'nc.exe',
            'ncat.exe',
            'psexec.exe',
            'psexesvc.exe',
            'tor.exe',
            'vnc.exe',
            'vncservice.exe',
            'vncviewer.exe',
            'winexesvc.exe',
            'nmap.exe',
            'psinfo.exe'
          )
    - name: Suspicious ports
      def: net.dport in
          (
            22,
            23,
            25,
            143,
            3389,
            5800,
            5900,
            444,
            1080,
            3128,
            8080,
            1723,
            9001,
            9030
          )

- group: Suspicious network-connecting binaries
  selector:
    type: Connect
  enabled: true
  policy: exclude
  relation: or
  from-strings:
    - name: Microsoft binaries
      def: ps.exe startswith 'C:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\'
              or
           ps.exe endswith 'AppData\\Local\\Microsoft\\Teams\\current\\Teams.exe'
              or
           net.dip.names endswith
           (
              '.microsoft.com',
              'microsoft.com.akadns.net',
              'microsoft.com.nsatc.net'
           )
    - name: OCSP protocol known addresses
      def: net.dip in (23.4.43.27, 72.21.91.29)
    - name: Loopback addresses
      def: net.dip = 127.0.0.1 or net.dip startswith 'fe80:0:0:0'