blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://github.com/rabbitstack/fibratus/discussions/new/choose
    about: Please ask and answer questions in the project Github Discussions
