/*
 * Copyright 2021-present by Nedim Sabic Sabic
 * https://www.fibratus.io
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package event

import (
	"expvar"
	"sync"
	"time"

	"github.com/rabbitstack/fibratus/pkg/event/params"
	"github.com/rabbitstack/fibratus/pkg/util/multierror"
	log "github.com/sirupsen/logrus"
)

// maxQueueTTLPeriod specifies the maximum period
// for the events to reside in the bucket queue
var maxQueueTTLPeriod = time.Millisecond * 500

// flusherInterval specifies the interval for the queue flushing
var flusherInterval = time.Millisecond * 250

// stackwalkFlushes computes overall flushes for unmatched stackwalk events
var stackwalkFlushes = expvar.NewInt("stackwalk.flushes")

// stackwalkFlushesProcs computes overall flushes for unmatched stackwalk events per process
var stackwalkFlushesProcs = expvar.NewMap("stackwalk.flushes.procs")

// stackwalkFlushesEvents computes overall flushes for unmatched stackwalks per event type
var stackwalkFlushesEvents = expvar.NewMap("stackwalk.flushes.events")

// stackwalkUnordered counts the unordered stackwalk matches
var stackwalkUnorderedMatches = expvar.NewInt("stackwalk.unordered.matches")

// stackwalkUnorderedEnqueued counts enqueued unordered stackwalk matches
var stackwalkUnorderedEnqueued = expvar.NewInt("stackwalk.unordered.enqueued")

// stackwalkSurrogateProcessHits counts the number of hits where the callstack is attributed from
// the surrogate thread creation event
var stackwalkSurrogateProcessHits = expvar.NewInt("stackwalk.surrogate.process.hits")

// StackwalkDecorator maintains a per-timestamp buckets where
// events eligible for stack enrichment are queued. Upon arrival
// of the respective stack walk event, the acting event is
// popped from the bucket and enriched with return addresses
// which are later subject to symbolization.
type StackwalkDecorator struct {
	buckets map[uint64]*Event
	q       *Queue
	mux     sync.Mutex

	flusher *time.Ticker
	quit    chan struct{}

	procs map[uint32]*Event // stores CreateProcess events with surrogate parent
}

// NewStackwalkDecorator creates a new callstack return
// addresses decorator which receives the event queue
// for long-standing event flushing.
func NewStackwalkDecorator(q *Queue) *StackwalkDecorator {
	s := &StackwalkDecorator{
		q:       q,
		buckets: make(map[uint64]*Event),
		procs:   make(map[uint32]*Event),
		flusher: time.NewTicker(flusherInterval),
		quit:    make(chan struct{}, 1),
	}

	go s.doFlush()

	return s
}

// Push pushes a new event to the queue.
func (s *StackwalkDecorator) Push(e *Event) {
	s.mux.Lock()
	defer s.mux.Unlock()

	// the process is created on behalf of brokered
	// process and the callstack return addresses
	// need to be obtained from the surrogate process
	if e.IsSurrogateProcess() {
		s.procs[e.Params.MustGetPid()] = e
	}

	id := e.RawTimestamp()

	// check if we have the previous stack walk event
	if evt, ok := s.buckets[id]; ok && evt.IsStackWalk() {
		stackwalkUnorderedMatches.Add(1)
		callstack := evt.Params.MustGetSlice(params.Callstack)
		e.AppendParam(params.Callstack, params.Slice, callstack)
		delete(s.buckets, id)
		_ = s.q.push(e)
	} else {
		// store the event to the bucket indexed by stack id
		s.buckets[id] = e
	}
}

// Pop receives the stack walk event and pops the oldest
// originating event with the same pid,tid tuple formerly
// coined as stack identifier. The originating event is then
// decorated with callstack return addresses.
func (s *StackwalkDecorator) Pop(e *Event) *Event {
	s.mux.Lock()
	defer s.mux.Unlock()

	id := e.Params.MustGetUint64(params.CallstackTimestamp)
	evt, ok := s.buckets[id]
	if !ok {
		// enqueue if the stack walk arrived out of order
		if e.Params.MustGetPid() != currentPid {
			s.buckets[id] = e
			stackwalkUnorderedEnqueued.Add(1)
		}
		return e
	}
	delete(s.buckets, id)

	if evt.IsSurrogateProcess() && s.procs[evt.Params.MustGetPid()] != nil {
		delete(s.procs, evt.Params.MustGetPid())
	}

	callstack := e.Params.MustGetSlice(params.Callstack)
	evt.AppendParam(params.Callstack, params.Slice, callstack)

	// obtain the callstack from the CreateThread event
	// generated by the surrogate/brokered process, such as
	// Secondary Logon.
	// If the remote process id is present in the procs map
	// the stack is attached to the cached event and then
	// pushed to the queue immediately
	if evt.IsCreateRemoteThread() {
		pid := evt.Params.MustGetPid()
		ev, ok := s.procs[pid]
		if ok {
			ev.AppendParam(params.Callstack, params.Slice, callstack)
			_ = s.q.push(ev)
			delete(s.procs, pid)
			delete(s.buckets, ev.RawTimestamp())
			stackwalkSurrogateProcessHits.Add(1)
		}
	}

	return evt
}

// Stop shutdowns the stack walk decorator flusher.
func (s *StackwalkDecorator) Stop() {
	s.quit <- struct{}{}
}

func (s *StackwalkDecorator) doFlush() {
	for {
		select {
		case <-s.flusher.C:
			errs := s.flush()
			if len(errs) > 0 {
				log.Warnf("callstack: unable to flush queued events: %v", multierror.Wrap(errs...))
			}
		case <-s.quit:
			return
		}
	}
}

// flush pushes events to the event queue if they have
// been living in the queue more than the maximum allowed
// TTL period.
func (s *StackwalkDecorator) flush() []error {
	s.mux.Lock()

	if len(s.buckets) == 0 {
		s.mux.Unlock()
		return nil
	}

	expired := make([]*Event, 0)

	for id, evt := range s.buckets {
		if time.Since(evt.Timestamp) < maxQueueTTLPeriod {
			continue
		}
		expired = append(expired, evt)
		delete(s.buckets, id)
	}

	s.mux.Unlock()
	errs := make([]error, 0)

	// push expired events without holding the mutex.
	// This allows incoming Push()/Pop() calls to proceed
	// while the channel send may block briefly
	for _, evt := range expired {
		if evt.IsStackWalk() {
			continue
		}
		stackwalkFlushes.Add(1)

		err := s.q.push(evt)
		if err != nil {
			errs = append(errs, err)
		}
		if evt.PS != nil {
			stackwalkFlushesProcs.Add(evt.PS.Name, 1)
		}
		stackwalkFlushesEvents.Add(evt.Name, 1)
	}

	return errs
}
