- group: remote connection and command shell execution
  policy: sequence
  rules:
    - name: establish remote connection
      condition: >
        kevt.name = 'Connect'
          and
          not
        cidr_contains(
          net.dip,
          '10.0.0.0/8',
          '172.16.0.0/12',
          '172.17.0.0/16',
          '192.168.0.0/16')
    - name: spawn command shell
      max-span: 1m
      condition: >
        kevt.name = 'CreateProcess'
          and
        ps.pid = $1.ps.pid
          and
        ps.sibling.name in ('cmd.exe', 'powershell.exe')
  action: >
    {{ emit "Command shell spawned after remote connection"
      (printf "%s process spawned a command shell after connecting to %s" .Kevts.k2.PS.Exe .Kevts.k1.Kparams.dip)
    }}
