// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type CloneScratchValue struct {
	_         structs.HostLayout
	Arg0      uint64
	Arg1      uint64
	Arg2      uint64
	Arg3      uint64
	Flags     uint64
	Truncated uint32
	Pad       uint32
	Filename  [256]uint8
	Aux       [256]uint8
}

// LoadClone returns the embedded CollectionSpec for Clone.
func LoadClone() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CloneBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Clone: %w", err)
	}

	return spec, err
}

// LoadCloneObjects loads Clone and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CloneObjects
//	*ClonePrograms
//	*CloneMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCloneObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadClone()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CloneSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CloneSpecs struct {
	CloneProgramSpecs
	CloneMapSpecs
	CloneVariableSpecs
}

// CloneProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CloneProgramSpecs struct {
	HandleSchedProcessFork *ebpf.ProgramSpec `ebpf:"handle_sched_process_fork"`
	HandleSysEnterClone    *ebpf.ProgramSpec `ebpf:"handle_sys_enter_clone"`
	HandleSysEnterClone3   *ebpf.ProgramSpec `ebpf:"handle_sys_enter_clone3"`
	HandleSysEnterFork     *ebpf.ProgramSpec `ebpf:"handle_sys_enter_fork"`
	HandleSysEnterVfork    *ebpf.ProgramSpec `ebpf:"handle_sys_enter_vfork"`
	HandleSysExitClone     *ebpf.ProgramSpec `ebpf:"handle_sys_exit_clone"`
	HandleSysExitClone3    *ebpf.ProgramSpec `ebpf:"handle_sys_exit_clone3"`
	HandleSysExitFork      *ebpf.ProgramSpec `ebpf:"handle_sys_exit_fork"`
	HandleSysExitVfork     *ebpf.ProgramSpec `ebpf:"handle_sys_exit_vfork"`
}

// CloneMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CloneMapSpecs struct {
	DropCount   *ebpf.MapSpec `ebpf:"drop_count"`
	Enabled     *ebpf.MapSpec `ebpf:"enabled"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	Scratch     *ebpf.MapSpec `ebpf:"scratch"`
	ScratchHeap *ebpf.MapSpec `ebpf:"scratch_heap"`
}

// CloneVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CloneVariableSpecs struct {
}

// CloneObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCloneObjects or ebpf.CollectionSpec.LoadAndAssign.
type CloneObjects struct {
	ClonePrograms
	CloneMaps
	CloneVariables
}

func (o *CloneObjects) Close() error {
	return _CloneClose(
		&o.ClonePrograms,
		&o.CloneMaps,
	)
}

// CloneMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCloneObjects or ebpf.CollectionSpec.LoadAndAssign.
type CloneMaps struct {
	DropCount   *ebpf.Map `ebpf:"drop_count"`
	Enabled     *ebpf.Map `ebpf:"enabled"`
	Events      *ebpf.Map `ebpf:"events"`
	Scratch     *ebpf.Map `ebpf:"scratch"`
	ScratchHeap *ebpf.Map `ebpf:"scratch_heap"`
}

func (m *CloneMaps) Close() error {
	return _CloneClose(
		m.DropCount,
		m.Enabled,
		m.Events,
		m.Scratch,
		m.ScratchHeap,
	)
}

// CloneVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadCloneObjects or ebpf.CollectionSpec.LoadAndAssign.
type CloneVariables struct {
}

// ClonePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCloneObjects or ebpf.CollectionSpec.LoadAndAssign.
type ClonePrograms struct {
	HandleSchedProcessFork *ebpf.Program `ebpf:"handle_sched_process_fork"`
	HandleSysEnterClone    *ebpf.Program `ebpf:"handle_sys_enter_clone"`
	HandleSysEnterClone3   *ebpf.Program `ebpf:"handle_sys_enter_clone3"`
	HandleSysEnterFork     *ebpf.Program `ebpf:"handle_sys_enter_fork"`
	HandleSysEnterVfork    *ebpf.Program `ebpf:"handle_sys_enter_vfork"`
	HandleSysExitClone     *ebpf.Program `ebpf:"handle_sys_exit_clone"`
	HandleSysExitClone3    *ebpf.Program `ebpf:"handle_sys_exit_clone3"`
	HandleSysExitFork      *ebpf.Program `ebpf:"handle_sys_exit_fork"`
	HandleSysExitVfork     *ebpf.Program `ebpf:"handle_sys_exit_vfork"`
}

func (p *ClonePrograms) Close() error {
	return _CloneClose(
		p.HandleSchedProcessFork,
		p.HandleSysEnterClone,
		p.HandleSysEnterClone3,
		p.HandleSysEnterFork,
		p.HandleSysEnterVfork,
		p.HandleSysExitClone,
		p.HandleSysExitClone3,
		p.HandleSysExitFork,
		p.HandleSysExitVfork,
	)
}

func _CloneClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed clone_bpfeb.o
var _CloneBytes []byte
