// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type CtlApproverFileKey struct {
	_    structs.HostLayout
	Gen  uint32
	Type uint32
	Path [256]uint8
}

type CtlApproverLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Path      [256]uint8
}

type CtlApproverPidKey struct {
	_    structs.HostLayout
	Gen  uint32
	Type uint32
	Pid  uint64
}

type CtlApproverPortKey struct {
	_    structs.HostLayout
	Gen  uint32
	Type uint32
	Port uint16
	Pad  uint16
}

type CtlScratchValue struct {
	_         structs.HostLayout
	Arg0      uint64
	Arg1      uint64
	Arg2      uint64
	Arg3      uint64
	Flags     uint64
	Truncated uint32
	Pad       uint32
	Filename  [256]uint8
	Aux       [256]uint8
}

// LoadCtl returns the embedded CollectionSpec for Ctl.
func LoadCtl() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CtlBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Ctl: %w", err)
	}

	return spec, err
}

// LoadCtlObjects loads Ctl and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CtlObjects
//	*CtlPrograms
//	*CtlMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCtlObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadCtl()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CtlSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CtlSpecs struct {
	CtlProgramSpecs
	CtlMapSpecs
	CtlVariableSpecs
}

// CtlProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CtlProgramSpecs struct {
	HandleSysExit *ebpf.ProgramSpec `ebpf:"handle_sys_exit"`
}

// CtlMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CtlMapSpecs struct {
	ApproverFileEq   *ebpf.MapSpec `ebpf:"approver_file_eq"`
	ApproverFileHeap *ebpf.MapSpec `ebpf:"approver_file_heap"`
	ApproverFilePre0 *ebpf.MapSpec `ebpf:"approver_file_pre_0"`
	ApproverFilePre1 *ebpf.MapSpec `ebpf:"approver_file_pre_1"`
	ApproverGen      *ebpf.MapSpec `ebpf:"approver_gen"`
	ApproverLpmHeap  *ebpf.MapSpec `ebpf:"approver_lpm_heap"`
	ApproverMode     *ebpf.MapSpec `ebpf:"approver_mode"`
	ApproverPid      *ebpf.MapSpec `ebpf:"approver_pid"`
	ApproverPort     *ebpf.MapSpec `ebpf:"approver_port"`
	ApproverReject   *ebpf.MapSpec `ebpf:"approver_reject"`
	DropCount        *ebpf.MapSpec `ebpf:"drop_count"`
	Enabled          *ebpf.MapSpec `ebpf:"enabled"`
	Events           *ebpf.MapSpec `ebpf:"events"`
	Scratch          *ebpf.MapSpec `ebpf:"scratch"`
	ScratchHeap      *ebpf.MapSpec `ebpf:"scratch_heap"`
}

// CtlVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CtlVariableSpecs struct {
}

// CtlObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCtlObjects or ebpf.CollectionSpec.LoadAndAssign.
type CtlObjects struct {
	CtlPrograms
	CtlMaps
	CtlVariables
}

func (o *CtlObjects) Close() error {
	return _CtlClose(
		&o.CtlPrograms,
		&o.CtlMaps,
	)
}

// CtlMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCtlObjects or ebpf.CollectionSpec.LoadAndAssign.
type CtlMaps struct {
	ApproverFileEq   *ebpf.Map `ebpf:"approver_file_eq"`
	ApproverFileHeap *ebpf.Map `ebpf:"approver_file_heap"`
	ApproverFilePre0 *ebpf.Map `ebpf:"approver_file_pre_0"`
	ApproverFilePre1 *ebpf.Map `ebpf:"approver_file_pre_1"`
	ApproverGen      *ebpf.Map `ebpf:"approver_gen"`
	ApproverLpmHeap  *ebpf.Map `ebpf:"approver_lpm_heap"`
	ApproverMode     *ebpf.Map `ebpf:"approver_mode"`
	ApproverPid      *ebpf.Map `ebpf:"approver_pid"`
	ApproverPort     *ebpf.Map `ebpf:"approver_port"`
	ApproverReject   *ebpf.Map `ebpf:"approver_reject"`
	DropCount        *ebpf.Map `ebpf:"drop_count"`
	Enabled          *ebpf.Map `ebpf:"enabled"`
	Events           *ebpf.Map `ebpf:"events"`
	Scratch          *ebpf.Map `ebpf:"scratch"`
	ScratchHeap      *ebpf.Map `ebpf:"scratch_heap"`
}

func (m *CtlMaps) Close() error {
	return _CtlClose(
		m.ApproverFileEq,
		m.ApproverFileHeap,
		m.ApproverFilePre0,
		m.ApproverFilePre1,
		m.ApproverGen,
		m.ApproverLpmHeap,
		m.ApproverMode,
		m.ApproverPid,
		m.ApproverPort,
		m.ApproverReject,
		m.DropCount,
		m.Enabled,
		m.Events,
		m.Scratch,
		m.ScratchHeap,
	)
}

// CtlVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadCtlObjects or ebpf.CollectionSpec.LoadAndAssign.
type CtlVariables struct {
}

// CtlPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCtlObjects or ebpf.CollectionSpec.LoadAndAssign.
type CtlPrograms struct {
	HandleSysExit *ebpf.Program `ebpf:"handle_sys_exit"`
}

func (p *CtlPrograms) Close() error {
	return _CtlClose(
		p.HandleSysExit,
	)
}

func _CtlClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ctl_bpfel.o
var _CtlBytes []byte
