// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ExecveApproverFileKey struct {
	_    structs.HostLayout
	Gen  uint32
	Type uint32
	Path [256]uint8
}

type ExecveApproverLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Path      [256]uint8
}

type ExecveApproverPidKey struct {
	_    structs.HostLayout
	Gen  uint32
	Type uint32
	Pid  uint64
}

type ExecveApproverPortKey struct {
	_    structs.HostLayout
	Gen  uint32
	Type uint32
	Port uint16
	Pad  uint16
}

type ExecveScratchValue struct {
	_         structs.HostLayout
	Arg0      uint64
	Arg1      uint64
	Arg2      uint64
	Arg3      uint64
	Flags     uint64
	Truncated uint32
	Pad       uint32
	Filename  [256]uint8
	Aux       [256]uint8
}

// LoadExecve returns the embedded CollectionSpec for Execve.
func LoadExecve() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExecveBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Execve: %w", err)
	}

	return spec, err
}

// LoadExecveObjects loads Execve and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ExecveObjects
//	*ExecvePrograms
//	*ExecveMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadExecveObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadExecve()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ExecveSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecveSpecs struct {
	ExecveProgramSpecs
	ExecveMapSpecs
	ExecveVariableSpecs
}

// ExecveProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecveProgramSpecs struct {
	HandleSysEnterExecve   *ebpf.ProgramSpec `ebpf:"handle_sys_enter_execve"`
	HandleSysEnterExecveat *ebpf.ProgramSpec `ebpf:"handle_sys_enter_execveat"`
	HandleSysExitExecve    *ebpf.ProgramSpec `ebpf:"handle_sys_exit_execve"`
	HandleSysExitExecveat  *ebpf.ProgramSpec `ebpf:"handle_sys_exit_execveat"`
}

// ExecveMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecveMapSpecs struct {
	ApproverFileEq   *ebpf.MapSpec `ebpf:"approver_file_eq"`
	ApproverFileHeap *ebpf.MapSpec `ebpf:"approver_file_heap"`
	ApproverFilePre0 *ebpf.MapSpec `ebpf:"approver_file_pre_0"`
	ApproverFilePre1 *ebpf.MapSpec `ebpf:"approver_file_pre_1"`
	ApproverGen      *ebpf.MapSpec `ebpf:"approver_gen"`
	ApproverLpmHeap  *ebpf.MapSpec `ebpf:"approver_lpm_heap"`
	ApproverMode     *ebpf.MapSpec `ebpf:"approver_mode"`
	ApproverPid      *ebpf.MapSpec `ebpf:"approver_pid"`
	ApproverPort     *ebpf.MapSpec `ebpf:"approver_port"`
	ApproverReject   *ebpf.MapSpec `ebpf:"approver_reject"`
	DropCount        *ebpf.MapSpec `ebpf:"drop_count"`
	Enabled          *ebpf.MapSpec `ebpf:"enabled"`
	Events           *ebpf.MapSpec `ebpf:"events"`
	Scratch          *ebpf.MapSpec `ebpf:"scratch"`
	ScratchHeap      *ebpf.MapSpec `ebpf:"scratch_heap"`
}

// ExecveVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecveVariableSpecs struct {
}

// ExecveObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadExecveObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecveObjects struct {
	ExecvePrograms
	ExecveMaps
	ExecveVariables
}

func (o *ExecveObjects) Close() error {
	return _ExecveClose(
		&o.ExecvePrograms,
		&o.ExecveMaps,
	)
}

// ExecveMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadExecveObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecveMaps struct {
	ApproverFileEq   *ebpf.Map `ebpf:"approver_file_eq"`
	ApproverFileHeap *ebpf.Map `ebpf:"approver_file_heap"`
	ApproverFilePre0 *ebpf.Map `ebpf:"approver_file_pre_0"`
	ApproverFilePre1 *ebpf.Map `ebpf:"approver_file_pre_1"`
	ApproverGen      *ebpf.Map `ebpf:"approver_gen"`
	ApproverLpmHeap  *ebpf.Map `ebpf:"approver_lpm_heap"`
	ApproverMode     *ebpf.Map `ebpf:"approver_mode"`
	ApproverPid      *ebpf.Map `ebpf:"approver_pid"`
	ApproverPort     *ebpf.Map `ebpf:"approver_port"`
	ApproverReject   *ebpf.Map `ebpf:"approver_reject"`
	DropCount        *ebpf.Map `ebpf:"drop_count"`
	Enabled          *ebpf.Map `ebpf:"enabled"`
	Events           *ebpf.Map `ebpf:"events"`
	Scratch          *ebpf.Map `ebpf:"scratch"`
	ScratchHeap      *ebpf.Map `ebpf:"scratch_heap"`
}

func (m *ExecveMaps) Close() error {
	return _ExecveClose(
		m.ApproverFileEq,
		m.ApproverFileHeap,
		m.ApproverFilePre0,
		m.ApproverFilePre1,
		m.ApproverGen,
		m.ApproverLpmHeap,
		m.ApproverMode,
		m.ApproverPid,
		m.ApproverPort,
		m.ApproverReject,
		m.DropCount,
		m.Enabled,
		m.Events,
		m.Scratch,
		m.ScratchHeap,
	)
}

// ExecveVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadExecveObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecveVariables struct {
}

// ExecvePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadExecveObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecvePrograms struct {
	HandleSysEnterExecve   *ebpf.Program `ebpf:"handle_sys_enter_execve"`
	HandleSysEnterExecveat *ebpf.Program `ebpf:"handle_sys_enter_execveat"`
	HandleSysExitExecve    *ebpf.Program `ebpf:"handle_sys_exit_execve"`
	HandleSysExitExecveat  *ebpf.Program `ebpf:"handle_sys_exit_execveat"`
}

func (p *ExecvePrograms) Close() error {
	return _ExecveClose(
		p.HandleSysEnterExecve,
		p.HandleSysEnterExecveat,
		p.HandleSysExitExecve,
		p.HandleSysExitExecveat,
	)
}

func _ExecveClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed execve_bpfeb.o
var _ExecveBytes []byte
