// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ExitScratchValue struct {
	_         structs.HostLayout
	Arg0      uint64
	Arg1      uint64
	Arg2      uint64
	Arg3      uint64
	Flags     uint64
	Truncated uint32
	Pad       uint32
	Filename  [256]uint8
	Aux       [256]uint8
}

// LoadExit returns the embedded CollectionSpec for Exit.
func LoadExit() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExitBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Exit: %w", err)
	}

	return spec, err
}

// LoadExitObjects loads Exit and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ExitObjects
//	*ExitPrograms
//	*ExitMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadExitObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadExit()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ExitSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExitSpecs struct {
	ExitProgramSpecs
	ExitMapSpecs
	ExitVariableSpecs
}

// ExitProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExitProgramSpecs struct {
	HandleSchedProcessExit *ebpf.ProgramSpec `ebpf:"handle_sched_process_exit"`
}

// ExitMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExitMapSpecs struct {
	DropCount   *ebpf.MapSpec `ebpf:"drop_count"`
	Enabled     *ebpf.MapSpec `ebpf:"enabled"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	Scratch     *ebpf.MapSpec `ebpf:"scratch"`
	ScratchHeap *ebpf.MapSpec `ebpf:"scratch_heap"`
}

// ExitVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExitVariableSpecs struct {
}

// ExitObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadExitObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExitObjects struct {
	ExitPrograms
	ExitMaps
	ExitVariables
}

func (o *ExitObjects) Close() error {
	return _ExitClose(
		&o.ExitPrograms,
		&o.ExitMaps,
	)
}

// ExitMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadExitObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExitMaps struct {
	DropCount   *ebpf.Map `ebpf:"drop_count"`
	Enabled     *ebpf.Map `ebpf:"enabled"`
	Events      *ebpf.Map `ebpf:"events"`
	Scratch     *ebpf.Map `ebpf:"scratch"`
	ScratchHeap *ebpf.Map `ebpf:"scratch_heap"`
}

func (m *ExitMaps) Close() error {
	return _ExitClose(
		m.DropCount,
		m.Enabled,
		m.Events,
		m.Scratch,
		m.ScratchHeap,
	)
}

// ExitVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadExitObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExitVariables struct {
}

// ExitPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadExitObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExitPrograms struct {
	HandleSchedProcessExit *ebpf.Program `ebpf:"handle_sched_process_exit"`
}

func (p *ExitPrograms) Close() error {
	return _ExitClose(
		p.HandleSchedProcessExit,
	)
}

func _ExitClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed exit_bpfeb.o
var _ExitBytes []byte
