// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type FileScratchValue struct {
	_         structs.HostLayout
	Arg0      uint64
	Arg1      uint64
	Arg2      uint64
	Arg3      uint64
	Flags     uint64
	Truncated uint32
	Pad       uint32
	Filename  [256]uint8
	Aux       [256]uint8
}

// LoadFile returns the embedded CollectionSpec for File.
func LoadFile() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FileBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load File: %w", err)
	}

	return spec, err
}

// LoadFileObjects loads File and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*FileObjects
//	*FilePrograms
//	*FileMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadFileObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadFile()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// FileSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileSpecs struct {
	FileProgramSpecs
	FileMapSpecs
	FileVariableSpecs
}

// FileProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileProgramSpecs struct {
	HandleSysEnterOpen      *ebpf.ProgramSpec `ebpf:"handle_sys_enter_open"`
	HandleSysEnterOpenat    *ebpf.ProgramSpec `ebpf:"handle_sys_enter_openat"`
	HandleSysEnterOpenat2   *ebpf.ProgramSpec `ebpf:"handle_sys_enter_openat2"`
	HandleSysEnterRename    *ebpf.ProgramSpec `ebpf:"handle_sys_enter_rename"`
	HandleSysEnterRenameat  *ebpf.ProgramSpec `ebpf:"handle_sys_enter_renameat"`
	HandleSysEnterRenameat2 *ebpf.ProgramSpec `ebpf:"handle_sys_enter_renameat2"`
	HandleSysEnterUnlink    *ebpf.ProgramSpec `ebpf:"handle_sys_enter_unlink"`
	HandleSysEnterUnlinkat  *ebpf.ProgramSpec `ebpf:"handle_sys_enter_unlinkat"`
	HandleSysExitOpen       *ebpf.ProgramSpec `ebpf:"handle_sys_exit_open"`
	HandleSysExitOpenat     *ebpf.ProgramSpec `ebpf:"handle_sys_exit_openat"`
	HandleSysExitOpenat2    *ebpf.ProgramSpec `ebpf:"handle_sys_exit_openat2"`
	HandleSysExitRename     *ebpf.ProgramSpec `ebpf:"handle_sys_exit_rename"`
	HandleSysExitRenameat   *ebpf.ProgramSpec `ebpf:"handle_sys_exit_renameat"`
	HandleSysExitRenameat2  *ebpf.ProgramSpec `ebpf:"handle_sys_exit_renameat2"`
	HandleSysExitUnlink     *ebpf.ProgramSpec `ebpf:"handle_sys_exit_unlink"`
	HandleSysExitUnlinkat   *ebpf.ProgramSpec `ebpf:"handle_sys_exit_unlinkat"`
}

// FileMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileMapSpecs struct {
	DropCount   *ebpf.MapSpec `ebpf:"drop_count"`
	Enabled     *ebpf.MapSpec `ebpf:"enabled"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	Scratch     *ebpf.MapSpec `ebpf:"scratch"`
	ScratchHeap *ebpf.MapSpec `ebpf:"scratch_heap"`
}

// FileVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileVariableSpecs struct {
}

// FileObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileObjects struct {
	FilePrograms
	FileMaps
	FileVariables
}

func (o *FileObjects) Close() error {
	return _FileClose(
		&o.FilePrograms,
		&o.FileMaps,
	)
}

// FileMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileMaps struct {
	DropCount   *ebpf.Map `ebpf:"drop_count"`
	Enabled     *ebpf.Map `ebpf:"enabled"`
	Events      *ebpf.Map `ebpf:"events"`
	Scratch     *ebpf.Map `ebpf:"scratch"`
	ScratchHeap *ebpf.Map `ebpf:"scratch_heap"`
}

func (m *FileMaps) Close() error {
	return _FileClose(
		m.DropCount,
		m.Enabled,
		m.Events,
		m.Scratch,
		m.ScratchHeap,
	)
}

// FileVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileVariables struct {
}

// FilePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type FilePrograms struct {
	HandleSysEnterOpen      *ebpf.Program `ebpf:"handle_sys_enter_open"`
	HandleSysEnterOpenat    *ebpf.Program `ebpf:"handle_sys_enter_openat"`
	HandleSysEnterOpenat2   *ebpf.Program `ebpf:"handle_sys_enter_openat2"`
	HandleSysEnterRename    *ebpf.Program `ebpf:"handle_sys_enter_rename"`
	HandleSysEnterRenameat  *ebpf.Program `ebpf:"handle_sys_enter_renameat"`
	HandleSysEnterRenameat2 *ebpf.Program `ebpf:"handle_sys_enter_renameat2"`
	HandleSysEnterUnlink    *ebpf.Program `ebpf:"handle_sys_enter_unlink"`
	HandleSysEnterUnlinkat  *ebpf.Program `ebpf:"handle_sys_enter_unlinkat"`
	HandleSysExitOpen       *ebpf.Program `ebpf:"handle_sys_exit_open"`
	HandleSysExitOpenat     *ebpf.Program `ebpf:"handle_sys_exit_openat"`
	HandleSysExitOpenat2    *ebpf.Program `ebpf:"handle_sys_exit_openat2"`
	HandleSysExitRename     *ebpf.Program `ebpf:"handle_sys_exit_rename"`
	HandleSysExitRenameat   *ebpf.Program `ebpf:"handle_sys_exit_renameat"`
	HandleSysExitRenameat2  *ebpf.Program `ebpf:"handle_sys_exit_renameat2"`
	HandleSysExitUnlink     *ebpf.Program `ebpf:"handle_sys_exit_unlink"`
	HandleSysExitUnlinkat   *ebpf.Program `ebpf:"handle_sys_exit_unlinkat"`
}

func (p *FilePrograms) Close() error {
	return _FileClose(
		p.HandleSysEnterOpen,
		p.HandleSysEnterOpenat,
		p.HandleSysEnterOpenat2,
		p.HandleSysEnterRename,
		p.HandleSysEnterRenameat,
		p.HandleSysEnterRenameat2,
		p.HandleSysEnterUnlink,
		p.HandleSysEnterUnlinkat,
		p.HandleSysExitOpen,
		p.HandleSysExitOpenat,
		p.HandleSysExitOpenat2,
		p.HandleSysExitRename,
		p.HandleSysExitRenameat,
		p.HandleSysExitRenameat2,
		p.HandleSysExitUnlink,
		p.HandleSysExitUnlinkat,
	)
}

func _FileClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed file_bpfeb.o
var _FileBytes []byte
