// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type MemScratchValue struct {
	_         structs.HostLayout
	Arg0      uint64
	Arg1      uint64
	Arg2      uint64
	Arg3      uint64
	Flags     uint64
	Truncated uint32
	Pad       uint32
	Filename  [256]uint8
	Aux       [256]uint8
}

// LoadMem returns the embedded CollectionSpec for Mem.
func LoadMem() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MemBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Mem: %w", err)
	}

	return spec, err
}

// LoadMemObjects loads Mem and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*MemObjects
//	*MemPrograms
//	*MemMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadMemObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadMem()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// MemSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemSpecs struct {
	MemProgramSpecs
	MemMapSpecs
	MemVariableSpecs
}

// MemProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemProgramSpecs struct {
	HandleSysEnterMmap            *ebpf.ProgramSpec `ebpf:"handle_sys_enter_mmap"`
	HandleSysEnterProcessVmReadv  *ebpf.ProgramSpec `ebpf:"handle_sys_enter_process_vm_readv"`
	HandleSysEnterProcessVmWritev *ebpf.ProgramSpec `ebpf:"handle_sys_enter_process_vm_writev"`
	HandleSysExitMmap             *ebpf.ProgramSpec `ebpf:"handle_sys_exit_mmap"`
	HandleSysExitProcessVmReadv   *ebpf.ProgramSpec `ebpf:"handle_sys_exit_process_vm_readv"`
	HandleSysExitProcessVmWritev  *ebpf.ProgramSpec `ebpf:"handle_sys_exit_process_vm_writev"`
}

// MemMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemMapSpecs struct {
	DropCount   *ebpf.MapSpec `ebpf:"drop_count"`
	Enabled     *ebpf.MapSpec `ebpf:"enabled"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	Scratch     *ebpf.MapSpec `ebpf:"scratch"`
	ScratchHeap *ebpf.MapSpec `ebpf:"scratch_heap"`
}

// MemVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemVariableSpecs struct {
}

// MemObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadMemObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemObjects struct {
	MemPrograms
	MemMaps
	MemVariables
}

func (o *MemObjects) Close() error {
	return _MemClose(
		&o.MemPrograms,
		&o.MemMaps,
	)
}

// MemMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadMemObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemMaps struct {
	DropCount   *ebpf.Map `ebpf:"drop_count"`
	Enabled     *ebpf.Map `ebpf:"enabled"`
	Events      *ebpf.Map `ebpf:"events"`
	Scratch     *ebpf.Map `ebpf:"scratch"`
	ScratchHeap *ebpf.Map `ebpf:"scratch_heap"`
}

func (m *MemMaps) Close() error {
	return _MemClose(
		m.DropCount,
		m.Enabled,
		m.Events,
		m.Scratch,
		m.ScratchHeap,
	)
}

// MemVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadMemObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemVariables struct {
}

// MemPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadMemObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemPrograms struct {
	HandleSysEnterMmap            *ebpf.Program `ebpf:"handle_sys_enter_mmap"`
	HandleSysEnterProcessVmReadv  *ebpf.Program `ebpf:"handle_sys_enter_process_vm_readv"`
	HandleSysEnterProcessVmWritev *ebpf.Program `ebpf:"handle_sys_enter_process_vm_writev"`
	HandleSysExitMmap             *ebpf.Program `ebpf:"handle_sys_exit_mmap"`
	HandleSysExitProcessVmReadv   *ebpf.Program `ebpf:"handle_sys_exit_process_vm_readv"`
	HandleSysExitProcessVmWritev  *ebpf.Program `ebpf:"handle_sys_exit_process_vm_writev"`
}

func (p *MemPrograms) Close() error {
	return _MemClose(
		p.HandleSysEnterMmap,
		p.HandleSysEnterProcessVmReadv,
		p.HandleSysEnterProcessVmWritev,
		p.HandleSysExitMmap,
		p.HandleSysExitProcessVmReadv,
		p.HandleSysExitProcessVmWritev,
	)
}

func _MemClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed mem_bpfeb.o
var _MemBytes []byte
