// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type NetApproverFileKey struct {
	_    structs.HostLayout
	Gen  uint32
	Type uint32
	Path [256]uint8
}

type NetApproverLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Path      [256]uint8
}

type NetApproverPidKey struct {
	_    structs.HostLayout
	Gen  uint32
	Type uint32
	Pid  uint64
}

type NetApproverPortKey struct {
	_    structs.HostLayout
	Gen  uint32
	Type uint32
	Port uint16
	Pad  uint16
}

type NetScratchValue struct {
	_         structs.HostLayout
	Arg0      uint64
	Arg1      uint64
	Arg2      uint64
	Arg3      uint64
	Flags     uint64
	Truncated uint32
	Pad       uint32
	Filename  [256]uint8
	Aux       [256]uint8
}

// LoadNet returns the embedded CollectionSpec for Net.
func LoadNet() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Net: %w", err)
	}

	return spec, err
}

// LoadNetObjects loads Net and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NetObjects
//	*NetPrograms
//	*NetMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNetObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNet()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NetSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetSpecs struct {
	NetProgramSpecs
	NetMapSpecs
	NetVariableSpecs
}

// NetProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetProgramSpecs struct {
	HandleSysEnterAccept  *ebpf.ProgramSpec `ebpf:"handle_sys_enter_accept"`
	HandleSysEnterAccept4 *ebpf.ProgramSpec `ebpf:"handle_sys_enter_accept4"`
	HandleSysEnterConnect *ebpf.ProgramSpec `ebpf:"handle_sys_enter_connect"`
	HandleSysExitAccept   *ebpf.ProgramSpec `ebpf:"handle_sys_exit_accept"`
	HandleSysExitAccept4  *ebpf.ProgramSpec `ebpf:"handle_sys_exit_accept4"`
	HandleSysExitConnect  *ebpf.ProgramSpec `ebpf:"handle_sys_exit_connect"`
}

// NetMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetMapSpecs struct {
	ApproverFileEq   *ebpf.MapSpec `ebpf:"approver_file_eq"`
	ApproverFileHeap *ebpf.MapSpec `ebpf:"approver_file_heap"`
	ApproverFilePre0 *ebpf.MapSpec `ebpf:"approver_file_pre_0"`
	ApproverFilePre1 *ebpf.MapSpec `ebpf:"approver_file_pre_1"`
	ApproverGen      *ebpf.MapSpec `ebpf:"approver_gen"`
	ApproverLpmHeap  *ebpf.MapSpec `ebpf:"approver_lpm_heap"`
	ApproverMode     *ebpf.MapSpec `ebpf:"approver_mode"`
	ApproverPid      *ebpf.MapSpec `ebpf:"approver_pid"`
	ApproverPort     *ebpf.MapSpec `ebpf:"approver_port"`
	ApproverReject   *ebpf.MapSpec `ebpf:"approver_reject"`
	DropCount        *ebpf.MapSpec `ebpf:"drop_count"`
	Enabled          *ebpf.MapSpec `ebpf:"enabled"`
	Events           *ebpf.MapSpec `ebpf:"events"`
	Scratch          *ebpf.MapSpec `ebpf:"scratch"`
	ScratchHeap      *ebpf.MapSpec `ebpf:"scratch_heap"`
}

// NetVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetVariableSpecs struct {
}

// NetObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNetObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetObjects struct {
	NetPrograms
	NetMaps
	NetVariables
}

func (o *NetObjects) Close() error {
	return _NetClose(
		&o.NetPrograms,
		&o.NetMaps,
	)
}

// NetMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNetObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetMaps struct {
	ApproverFileEq   *ebpf.Map `ebpf:"approver_file_eq"`
	ApproverFileHeap *ebpf.Map `ebpf:"approver_file_heap"`
	ApproverFilePre0 *ebpf.Map `ebpf:"approver_file_pre_0"`
	ApproverFilePre1 *ebpf.Map `ebpf:"approver_file_pre_1"`
	ApproverGen      *ebpf.Map `ebpf:"approver_gen"`
	ApproverLpmHeap  *ebpf.Map `ebpf:"approver_lpm_heap"`
	ApproverMode     *ebpf.Map `ebpf:"approver_mode"`
	ApproverPid      *ebpf.Map `ebpf:"approver_pid"`
	ApproverPort     *ebpf.Map `ebpf:"approver_port"`
	ApproverReject   *ebpf.Map `ebpf:"approver_reject"`
	DropCount        *ebpf.Map `ebpf:"drop_count"`
	Enabled          *ebpf.Map `ebpf:"enabled"`
	Events           *ebpf.Map `ebpf:"events"`
	Scratch          *ebpf.Map `ebpf:"scratch"`
	ScratchHeap      *ebpf.Map `ebpf:"scratch_heap"`
}

func (m *NetMaps) Close() error {
	return _NetClose(
		m.ApproverFileEq,
		m.ApproverFileHeap,
		m.ApproverFilePre0,
		m.ApproverFilePre1,
		m.ApproverGen,
		m.ApproverLpmHeap,
		m.ApproverMode,
		m.ApproverPid,
		m.ApproverPort,
		m.ApproverReject,
		m.DropCount,
		m.Enabled,
		m.Events,
		m.Scratch,
		m.ScratchHeap,
	)
}

// NetVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNetObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetVariables struct {
}

// NetPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNetObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetPrograms struct {
	HandleSysEnterAccept  *ebpf.Program `ebpf:"handle_sys_enter_accept"`
	HandleSysEnterAccept4 *ebpf.Program `ebpf:"handle_sys_enter_accept4"`
	HandleSysEnterConnect *ebpf.Program `ebpf:"handle_sys_enter_connect"`
	HandleSysExitAccept   *ebpf.Program `ebpf:"handle_sys_exit_accept"`
	HandleSysExitAccept4  *ebpf.Program `ebpf:"handle_sys_exit_accept4"`
	HandleSysExitConnect  *ebpf.Program `ebpf:"handle_sys_exit_connect"`
}

func (p *NetPrograms) Close() error {
	return _NetClose(
		p.HandleSysEnterAccept,
		p.HandleSysEnterAccept4,
		p.HandleSysEnterConnect,
		p.HandleSysExitAccept,
		p.HandleSysExitAccept4,
		p.HandleSysExitConnect,
	)
}

func _NetClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed net_bpfel.o
var _NetBytes []byte
