// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ProciterScratchValue struct {
	_         structs.HostLayout
	Arg0      uint64
	Arg1      uint64
	Arg2      uint64
	Arg3      uint64
	Flags     uint64
	Truncated uint32
	Pad       uint32
	Filename  [256]uint8
	Aux       [256]uint8
}

// LoadProciter returns the embedded CollectionSpec for Prociter.
func LoadProciter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProciterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Prociter: %w", err)
	}

	return spec, err
}

// LoadProciterObjects loads Prociter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ProciterObjects
//	*ProciterPrograms
//	*ProciterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadProciterObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadProciter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ProciterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProciterSpecs struct {
	ProciterProgramSpecs
	ProciterMapSpecs
	ProciterVariableSpecs
}

// ProciterProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProciterProgramSpecs struct {
	DumpTask *ebpf.ProgramSpec `ebpf:"dump_task"`
}

// ProciterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProciterMapSpecs struct {
	DropCount   *ebpf.MapSpec `ebpf:"drop_count"`
	Enabled     *ebpf.MapSpec `ebpf:"enabled"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	Scratch     *ebpf.MapSpec `ebpf:"scratch"`
	ScratchHeap *ebpf.MapSpec `ebpf:"scratch_heap"`
}

// ProciterVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProciterVariableSpecs struct {
}

// ProciterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadProciterObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProciterObjects struct {
	ProciterPrograms
	ProciterMaps
	ProciterVariables
}

func (o *ProciterObjects) Close() error {
	return _ProciterClose(
		&o.ProciterPrograms,
		&o.ProciterMaps,
	)
}

// ProciterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadProciterObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProciterMaps struct {
	DropCount   *ebpf.Map `ebpf:"drop_count"`
	Enabled     *ebpf.Map `ebpf:"enabled"`
	Events      *ebpf.Map `ebpf:"events"`
	Scratch     *ebpf.Map `ebpf:"scratch"`
	ScratchHeap *ebpf.Map `ebpf:"scratch_heap"`
}

func (m *ProciterMaps) Close() error {
	return _ProciterClose(
		m.DropCount,
		m.Enabled,
		m.Events,
		m.Scratch,
		m.ScratchHeap,
	)
}

// ProciterVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadProciterObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProciterVariables struct {
}

// ProciterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadProciterObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProciterPrograms struct {
	DumpTask *ebpf.Program `ebpf:"dump_task"`
}

func (p *ProciterPrograms) Close() error {
	return _ProciterClose(
		p.DumpTask,
	)
}

func _ProciterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed prociter_bpfeb.o
var _ProciterBytes []byte
