// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package spike

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadProciter returns the embedded CollectionSpec for prociter.
func loadProciter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProciterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load prociter: %w", err)
	}

	return spec, err
}

// loadProciterObjects loads prociter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*prociterObjects
//	*prociterPrograms
//	*prociterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProciterObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProciter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// prociterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type prociterSpecs struct {
	prociterProgramSpecs
	prociterMapSpecs
	prociterVariableSpecs
}

// prociterProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type prociterProgramSpecs struct {
	DumpTask *ebpf.ProgramSpec `ebpf:"dump_task"`
}

// prociterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type prociterMapSpecs struct {
	DropCount *ebpf.MapSpec `ebpf:"drop_count"`
	Events    *ebpf.MapSpec `ebpf:"events"`
}

// prociterVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type prociterVariableSpecs struct {
}

// prociterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProciterObjects or ebpf.CollectionSpec.LoadAndAssign.
type prociterObjects struct {
	prociterPrograms
	prociterMaps
	prociterVariables
}

func (o *prociterObjects) Close() error {
	return _ProciterClose(
		&o.prociterPrograms,
		&o.prociterMaps,
	)
}

// prociterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProciterObjects or ebpf.CollectionSpec.LoadAndAssign.
type prociterMaps struct {
	DropCount *ebpf.Map `ebpf:"drop_count"`
	Events    *ebpf.Map `ebpf:"events"`
}

func (m *prociterMaps) Close() error {
	return _ProciterClose(
		m.DropCount,
		m.Events,
	)
}

// prociterVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProciterObjects or ebpf.CollectionSpec.LoadAndAssign.
type prociterVariables struct {
}

// prociterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProciterObjects or ebpf.CollectionSpec.LoadAndAssign.
type prociterPrograms struct {
	DumpTask *ebpf.Program `ebpf:"dump_task"`
}

func (p *prociterPrograms) Close() error {
	return _ProciterClose(
		p.DumpTask,
	)
}

func _ProciterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed prociter_bpfel.o
var _ProciterBytes []byte
