/*
 * Copyright 2021-2026 by Nedim Sabic Sabic
 * https://www.fibratus.io
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package main

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"math"
	"os"
	"text/template"

	"github.com/Masterminds/sprig/v3"
)

// generate produces the message table embedded directly inside the binary.
func generate(w io.Writer) error {
	funcmap := sprig.TxtFuncMap()
	funcmap["N"] = func() (stream chan int) {
		stream = make(chan int)
		go func() {
			for i := 2; i <= math.MaxUint16; i++ {
				stream <- i
			}
			close(stream)
		}()
		return
	}
	t := template.Must(template.New("main").Funcs(funcmap).Parse(srcTemplate))
	err := t.Execute(w, nil)
	if err != nil {
		return fmt.Errorf("failed to execute template: %v", err)
	}
	return nil
}

func main() {
	var buf bytes.Buffer

	if err := generate(&buf); err != nil {
		log.Fatal(err)
	}

	if err := os.WriteFile("mc/fibratus.mc", buf.Bytes(), 0644); err != nil {
		log.Fatal(err)
	}
}

const srcTemplate = `
;// Code generated by 'go generate'; DO NOT EDIT.
MessageIdTypedef=DWORD

LanguageNames=(English=0x409:MSG00409)

MessageId=1
SymbolicName=Security
Language=English

{{- range $i, $_ := N }}
MessageId={{ $i }}
SymbolicName=Reserved{{ $i }}
Language=English
%1
.
{{- end }}
`
