- group: rouge processes
  enabled: true
  from-strings:
    - name: suspicious network activity
      def: kevt.category = 'net' and ps.name in ('at.exe', 'java.exe')
      action: |
        {{ kill .Kevt.Pid }}
