- group: rouge processes
  enabled: true
  rules:
    - name: suspicious network activity
      condition: kevt.category = 'net' and ps.name in ('at.exe', 'java.exe')
      action: |
        {{ kil .Kevt.PID }}
