// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type cloneScratchValue struct {
	_         structs.HostLayout
	Arg0      uint64
	Arg1      uint64
	Arg2      uint64
	Arg3      uint64
	Flags     uint64
	Truncated uint32
	Pad       uint32
	Filename  [256]uint8
	Aux       [256]uint8
}

// loadClone returns the embedded CollectionSpec for clone.
func loadClone() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CloneBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load clone: %w", err)
	}

	return spec, err
}

// loadCloneObjects loads clone and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*cloneObjects
//	*clonePrograms
//	*cloneMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCloneObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadClone()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// cloneSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cloneSpecs struct {
	cloneProgramSpecs
	cloneMapSpecs
	cloneVariableSpecs
}

// cloneProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cloneProgramSpecs struct {
	HandleSchedProcessFork *ebpf.ProgramSpec `ebpf:"handle_sched_process_fork"`
	HandleSysEnterClone    *ebpf.ProgramSpec `ebpf:"handle_sys_enter_clone"`
	HandleSysEnterClone3   *ebpf.ProgramSpec `ebpf:"handle_sys_enter_clone3"`
	HandleSysEnterFork     *ebpf.ProgramSpec `ebpf:"handle_sys_enter_fork"`
	HandleSysEnterVfork    *ebpf.ProgramSpec `ebpf:"handle_sys_enter_vfork"`
	HandleSysExitClone     *ebpf.ProgramSpec `ebpf:"handle_sys_exit_clone"`
	HandleSysExitClone3    *ebpf.ProgramSpec `ebpf:"handle_sys_exit_clone3"`
	HandleSysExitFork      *ebpf.ProgramSpec `ebpf:"handle_sys_exit_fork"`
	HandleSysExitVfork     *ebpf.ProgramSpec `ebpf:"handle_sys_exit_vfork"`
}

// cloneMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cloneMapSpecs struct {
	DropCount   *ebpf.MapSpec `ebpf:"drop_count"`
	Enabled     *ebpf.MapSpec `ebpf:"enabled"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	Scratch     *ebpf.MapSpec `ebpf:"scratch"`
	ScratchHeap *ebpf.MapSpec `ebpf:"scratch_heap"`
}

// cloneVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cloneVariableSpecs struct {
}

// cloneObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCloneObjects or ebpf.CollectionSpec.LoadAndAssign.
type cloneObjects struct {
	clonePrograms
	cloneMaps
	cloneVariables
}

func (o *cloneObjects) Close() error {
	return _CloneClose(
		&o.clonePrograms,
		&o.cloneMaps,
	)
}

// cloneMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCloneObjects or ebpf.CollectionSpec.LoadAndAssign.
type cloneMaps struct {
	DropCount   *ebpf.Map `ebpf:"drop_count"`
	Enabled     *ebpf.Map `ebpf:"enabled"`
	Events      *ebpf.Map `ebpf:"events"`
	Scratch     *ebpf.Map `ebpf:"scratch"`
	ScratchHeap *ebpf.Map `ebpf:"scratch_heap"`
}

func (m *cloneMaps) Close() error {
	return _CloneClose(
		m.DropCount,
		m.Enabled,
		m.Events,
		m.Scratch,
		m.ScratchHeap,
	)
}

// cloneVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCloneObjects or ebpf.CollectionSpec.LoadAndAssign.
type cloneVariables struct {
}

// clonePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCloneObjects or ebpf.CollectionSpec.LoadAndAssign.
type clonePrograms struct {
	HandleSchedProcessFork *ebpf.Program `ebpf:"handle_sched_process_fork"`
	HandleSysEnterClone    *ebpf.Program `ebpf:"handle_sys_enter_clone"`
	HandleSysEnterClone3   *ebpf.Program `ebpf:"handle_sys_enter_clone3"`
	HandleSysEnterFork     *ebpf.Program `ebpf:"handle_sys_enter_fork"`
	HandleSysEnterVfork    *ebpf.Program `ebpf:"handle_sys_enter_vfork"`
	HandleSysExitClone     *ebpf.Program `ebpf:"handle_sys_exit_clone"`
	HandleSysExitClone3    *ebpf.Program `ebpf:"handle_sys_exit_clone3"`
	HandleSysExitFork      *ebpf.Program `ebpf:"handle_sys_exit_fork"`
	HandleSysExitVfork     *ebpf.Program `ebpf:"handle_sys_exit_vfork"`
}

func (p *clonePrograms) Close() error {
	return _CloneClose(
		p.HandleSchedProcessFork,
		p.HandleSysEnterClone,
		p.HandleSysEnterClone3,
		p.HandleSysEnterFork,
		p.HandleSysEnterVfork,
		p.HandleSysExitClone,
		p.HandleSysExitClone3,
		p.HandleSysExitFork,
		p.HandleSysExitVfork,
	)
}

func _CloneClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed clone_bpfel.o
var _CloneBytes []byte
