// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ctlScratchValue struct {
	_         structs.HostLayout
	Arg0      uint64
	Arg1      uint64
	Arg2      uint64
	Arg3      uint64
	Flags     uint64
	Truncated uint32
	Pad       uint32
	Filename  [256]uint8
	Aux       [256]uint8
}

// loadCtl returns the embedded CollectionSpec for ctl.
func loadCtl() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CtlBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ctl: %w", err)
	}

	return spec, err
}

// loadCtlObjects loads ctl and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ctlObjects
//	*ctlPrograms
//	*ctlMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCtlObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCtl()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ctlSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ctlSpecs struct {
	ctlProgramSpecs
	ctlMapSpecs
	ctlVariableSpecs
}

// ctlProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ctlProgramSpecs struct {
	HandleSysExit *ebpf.ProgramSpec `ebpf:"handle_sys_exit"`
}

// ctlMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ctlMapSpecs struct {
	DropCount   *ebpf.MapSpec `ebpf:"drop_count"`
	Enabled     *ebpf.MapSpec `ebpf:"enabled"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	Scratch     *ebpf.MapSpec `ebpf:"scratch"`
	ScratchHeap *ebpf.MapSpec `ebpf:"scratch_heap"`
}

// ctlVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ctlVariableSpecs struct {
}

// ctlObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCtlObjects or ebpf.CollectionSpec.LoadAndAssign.
type ctlObjects struct {
	ctlPrograms
	ctlMaps
	ctlVariables
}

func (o *ctlObjects) Close() error {
	return _CtlClose(
		&o.ctlPrograms,
		&o.ctlMaps,
	)
}

// ctlMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCtlObjects or ebpf.CollectionSpec.LoadAndAssign.
type ctlMaps struct {
	DropCount   *ebpf.Map `ebpf:"drop_count"`
	Enabled     *ebpf.Map `ebpf:"enabled"`
	Events      *ebpf.Map `ebpf:"events"`
	Scratch     *ebpf.Map `ebpf:"scratch"`
	ScratchHeap *ebpf.Map `ebpf:"scratch_heap"`
}

func (m *ctlMaps) Close() error {
	return _CtlClose(
		m.DropCount,
		m.Enabled,
		m.Events,
		m.Scratch,
		m.ScratchHeap,
	)
}

// ctlVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCtlObjects or ebpf.CollectionSpec.LoadAndAssign.
type ctlVariables struct {
}

// ctlPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCtlObjects or ebpf.CollectionSpec.LoadAndAssign.
type ctlPrograms struct {
	HandleSysExit *ebpf.Program `ebpf:"handle_sys_exit"`
}

func (p *ctlPrograms) Close() error {
	return _CtlClose(
		p.HandleSysExit,
	)
}

func _CtlClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ctl_bpfel.o
var _CtlBytes []byte
