// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type execveScratchValue struct {
	_        structs.HostLayout
	Arg0     uint64
	Arg1     uint64
	Filename [256]uint8
}

// loadExecve returns the embedded CollectionSpec for execve.
func loadExecve() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExecveBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load execve: %w", err)
	}

	return spec, err
}

// loadExecveObjects loads execve and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*execveObjects
//	*execvePrograms
//	*execveMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadExecveObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadExecve()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// execveSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execveSpecs struct {
	execveProgramSpecs
	execveMapSpecs
	execveVariableSpecs
}

// execveProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execveProgramSpecs struct {
	HandleSysEnterExecve   *ebpf.ProgramSpec `ebpf:"handle_sys_enter_execve"`
	HandleSysEnterExecveat *ebpf.ProgramSpec `ebpf:"handle_sys_enter_execveat"`
	HandleSysExitExecve    *ebpf.ProgramSpec `ebpf:"handle_sys_exit_execve"`
	HandleSysExitExecveat  *ebpf.ProgramSpec `ebpf:"handle_sys_exit_execveat"`
}

// execveMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execveMapSpecs struct {
	DropCount *ebpf.MapSpec `ebpf:"drop_count"`
	Events    *ebpf.MapSpec `ebpf:"events"`
	Scratch   *ebpf.MapSpec `ebpf:"scratch"`
}

// execveVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execveVariableSpecs struct {
}

// execveObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadExecveObjects or ebpf.CollectionSpec.LoadAndAssign.
type execveObjects struct {
	execvePrograms
	execveMaps
	execveVariables
}

func (o *execveObjects) Close() error {
	return _ExecveClose(
		&o.execvePrograms,
		&o.execveMaps,
	)
}

// execveMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadExecveObjects or ebpf.CollectionSpec.LoadAndAssign.
type execveMaps struct {
	DropCount *ebpf.Map `ebpf:"drop_count"`
	Events    *ebpf.Map `ebpf:"events"`
	Scratch   *ebpf.Map `ebpf:"scratch"`
}

func (m *execveMaps) Close() error {
	return _ExecveClose(
		m.DropCount,
		m.Events,
		m.Scratch,
	)
}

// execveVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadExecveObjects or ebpf.CollectionSpec.LoadAndAssign.
type execveVariables struct {
}

// execvePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadExecveObjects or ebpf.CollectionSpec.LoadAndAssign.
type execvePrograms struct {
	HandleSysEnterExecve   *ebpf.Program `ebpf:"handle_sys_enter_execve"`
	HandleSysEnterExecveat *ebpf.Program `ebpf:"handle_sys_enter_execveat"`
	HandleSysExitExecve    *ebpf.Program `ebpf:"handle_sys_exit_execve"`
	HandleSysExitExecveat  *ebpf.Program `ebpf:"handle_sys_exit_execveat"`
}

func (p *execvePrograms) Close() error {
	return _ExecveClose(
		p.HandleSysEnterExecve,
		p.HandleSysEnterExecveat,
		p.HandleSysExitExecve,
		p.HandleSysExitExecveat,
	)
}

func _ExecveClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed execve_bpfel.o
var _ExecveBytes []byte
