// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type exitScratchValue struct {
	_         structs.HostLayout
	Arg0      uint64
	Arg1      uint64
	Arg2      uint64
	Arg3      uint64
	Flags     uint64
	Truncated uint32
	Pad       uint32
	Filename  [256]uint8
	Filename2 [256]uint8
}

// loadExit returns the embedded CollectionSpec for exit.
func loadExit() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExitBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load exit: %w", err)
	}

	return spec, err
}

// loadExitObjects loads exit and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*exitObjects
//	*exitPrograms
//	*exitMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadExitObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadExit()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// exitSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type exitSpecs struct {
	exitProgramSpecs
	exitMapSpecs
	exitVariableSpecs
}

// exitProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type exitProgramSpecs struct {
	HandleSchedProcessExit *ebpf.ProgramSpec `ebpf:"handle_sched_process_exit"`
}

// exitMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type exitMapSpecs struct {
	DropCount   *ebpf.MapSpec `ebpf:"drop_count"`
	Enabled     *ebpf.MapSpec `ebpf:"enabled"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	Scratch     *ebpf.MapSpec `ebpf:"scratch"`
	ScratchHeap *ebpf.MapSpec `ebpf:"scratch_heap"`
}

// exitVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type exitVariableSpecs struct {
}

// exitObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadExitObjects or ebpf.CollectionSpec.LoadAndAssign.
type exitObjects struct {
	exitPrograms
	exitMaps
	exitVariables
}

func (o *exitObjects) Close() error {
	return _ExitClose(
		&o.exitPrograms,
		&o.exitMaps,
	)
}

// exitMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadExitObjects or ebpf.CollectionSpec.LoadAndAssign.
type exitMaps struct {
	DropCount   *ebpf.Map `ebpf:"drop_count"`
	Enabled     *ebpf.Map `ebpf:"enabled"`
	Events      *ebpf.Map `ebpf:"events"`
	Scratch     *ebpf.Map `ebpf:"scratch"`
	ScratchHeap *ebpf.Map `ebpf:"scratch_heap"`
}

func (m *exitMaps) Close() error {
	return _ExitClose(
		m.DropCount,
		m.Enabled,
		m.Events,
		m.Scratch,
		m.ScratchHeap,
	)
}

// exitVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadExitObjects or ebpf.CollectionSpec.LoadAndAssign.
type exitVariables struct {
}

// exitPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadExitObjects or ebpf.CollectionSpec.LoadAndAssign.
type exitPrograms struct {
	HandleSchedProcessExit *ebpf.Program `ebpf:"handle_sched_process_exit"`
}

func (p *exitPrograms) Close() error {
	return _ExitClose(
		p.HandleSchedProcessExit,
	)
}

func _ExitClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed exit_bpfeb.o
var _ExitBytes []byte
