// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type memScratchValue struct {
	_         structs.HostLayout
	Arg0      uint64
	Arg1      uint64
	Arg2      uint64
	Arg3      uint64
	Flags     uint64
	Truncated uint32
	Pad       uint32
	Filename  [256]uint8
	Aux       [256]uint8
}

// loadMem returns the embedded CollectionSpec for mem.
func loadMem() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MemBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load mem: %w", err)
	}

	return spec, err
}

// loadMemObjects loads mem and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*memObjects
//	*memPrograms
//	*memMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMemObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadMem()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// memSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type memSpecs struct {
	memProgramSpecs
	memMapSpecs
	memVariableSpecs
}

// memProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type memProgramSpecs struct {
	HandleSysEnterMmap            *ebpf.ProgramSpec `ebpf:"handle_sys_enter_mmap"`
	HandleSysEnterProcessVmReadv  *ebpf.ProgramSpec `ebpf:"handle_sys_enter_process_vm_readv"`
	HandleSysEnterProcessVmWritev *ebpf.ProgramSpec `ebpf:"handle_sys_enter_process_vm_writev"`
	HandleSysExitMmap             *ebpf.ProgramSpec `ebpf:"handle_sys_exit_mmap"`
	HandleSysExitProcessVmReadv   *ebpf.ProgramSpec `ebpf:"handle_sys_exit_process_vm_readv"`
	HandleSysExitProcessVmWritev  *ebpf.ProgramSpec `ebpf:"handle_sys_exit_process_vm_writev"`
}

// memMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type memMapSpecs struct {
	DropCount   *ebpf.MapSpec `ebpf:"drop_count"`
	Enabled     *ebpf.MapSpec `ebpf:"enabled"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	Scratch     *ebpf.MapSpec `ebpf:"scratch"`
	ScratchHeap *ebpf.MapSpec `ebpf:"scratch_heap"`
}

// memVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type memVariableSpecs struct {
}

// memObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMemObjects or ebpf.CollectionSpec.LoadAndAssign.
type memObjects struct {
	memPrograms
	memMaps
	memVariables
}

func (o *memObjects) Close() error {
	return _MemClose(
		&o.memPrograms,
		&o.memMaps,
	)
}

// memMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMemObjects or ebpf.CollectionSpec.LoadAndAssign.
type memMaps struct {
	DropCount   *ebpf.Map `ebpf:"drop_count"`
	Enabled     *ebpf.Map `ebpf:"enabled"`
	Events      *ebpf.Map `ebpf:"events"`
	Scratch     *ebpf.Map `ebpf:"scratch"`
	ScratchHeap *ebpf.Map `ebpf:"scratch_heap"`
}

func (m *memMaps) Close() error {
	return _MemClose(
		m.DropCount,
		m.Enabled,
		m.Events,
		m.Scratch,
		m.ScratchHeap,
	)
}

// memVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadMemObjects or ebpf.CollectionSpec.LoadAndAssign.
type memVariables struct {
}

// memPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMemObjects or ebpf.CollectionSpec.LoadAndAssign.
type memPrograms struct {
	HandleSysEnterMmap            *ebpf.Program `ebpf:"handle_sys_enter_mmap"`
	HandleSysEnterProcessVmReadv  *ebpf.Program `ebpf:"handle_sys_enter_process_vm_readv"`
	HandleSysEnterProcessVmWritev *ebpf.Program `ebpf:"handle_sys_enter_process_vm_writev"`
	HandleSysExitMmap             *ebpf.Program `ebpf:"handle_sys_exit_mmap"`
	HandleSysExitProcessVmReadv   *ebpf.Program `ebpf:"handle_sys_exit_process_vm_readv"`
	HandleSysExitProcessVmWritev  *ebpf.Program `ebpf:"handle_sys_exit_process_vm_writev"`
}

func (p *memPrograms) Close() error {
	return _MemClose(
		p.HandleSysEnterMmap,
		p.HandleSysEnterProcessVmReadv,
		p.HandleSysEnterProcessVmWritev,
		p.HandleSysExitMmap,
		p.HandleSysExitProcessVmReadv,
		p.HandleSysExitProcessVmWritev,
	)
}

func _MemClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed mem_bpfel.o
var _MemBytes []byte
