// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type netScratchValue struct {
	_         structs.HostLayout
	Arg0      uint64
	Arg1      uint64
	Arg2      uint64
	Arg3      uint64
	Flags     uint64
	Truncated uint32
	Pad       uint32
	Filename  [256]uint8
	Filename2 [256]uint8
}

// loadNet returns the embedded CollectionSpec for net.
func loadNet() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load net: %w", err)
	}

	return spec, err
}

// loadNetObjects loads net and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*netObjects
//	*netPrograms
//	*netMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNet()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// netSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netSpecs struct {
	netProgramSpecs
	netMapSpecs
	netVariableSpecs
}

// netProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netProgramSpecs struct {
	HandleSysEnterAccept  *ebpf.ProgramSpec `ebpf:"handle_sys_enter_accept"`
	HandleSysEnterAccept4 *ebpf.ProgramSpec `ebpf:"handle_sys_enter_accept4"`
	HandleSysEnterConnect *ebpf.ProgramSpec `ebpf:"handle_sys_enter_connect"`
	HandleSysExitAccept   *ebpf.ProgramSpec `ebpf:"handle_sys_exit_accept"`
	HandleSysExitAccept4  *ebpf.ProgramSpec `ebpf:"handle_sys_exit_accept4"`
	HandleSysExitConnect  *ebpf.ProgramSpec `ebpf:"handle_sys_exit_connect"`
}

// netMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netMapSpecs struct {
	DropCount   *ebpf.MapSpec `ebpf:"drop_count"`
	Enabled     *ebpf.MapSpec `ebpf:"enabled"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	Scratch     *ebpf.MapSpec `ebpf:"scratch"`
	ScratchHeap *ebpf.MapSpec `ebpf:"scratch_heap"`
}

// netVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netVariableSpecs struct {
}

// netObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetObjects or ebpf.CollectionSpec.LoadAndAssign.
type netObjects struct {
	netPrograms
	netMaps
	netVariables
}

func (o *netObjects) Close() error {
	return _NetClose(
		&o.netPrograms,
		&o.netMaps,
	)
}

// netMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetObjects or ebpf.CollectionSpec.LoadAndAssign.
type netMaps struct {
	DropCount   *ebpf.Map `ebpf:"drop_count"`
	Enabled     *ebpf.Map `ebpf:"enabled"`
	Events      *ebpf.Map `ebpf:"events"`
	Scratch     *ebpf.Map `ebpf:"scratch"`
	ScratchHeap *ebpf.Map `ebpf:"scratch_heap"`
}

func (m *netMaps) Close() error {
	return _NetClose(
		m.DropCount,
		m.Enabled,
		m.Events,
		m.Scratch,
		m.ScratchHeap,
	)
}

// netVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNetObjects or ebpf.CollectionSpec.LoadAndAssign.
type netVariables struct {
}

// netPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetObjects or ebpf.CollectionSpec.LoadAndAssign.
type netPrograms struct {
	HandleSysEnterAccept  *ebpf.Program `ebpf:"handle_sys_enter_accept"`
	HandleSysEnterAccept4 *ebpf.Program `ebpf:"handle_sys_enter_accept4"`
	HandleSysEnterConnect *ebpf.Program `ebpf:"handle_sys_enter_connect"`
	HandleSysExitAccept   *ebpf.Program `ebpf:"handle_sys_exit_accept"`
	HandleSysExitAccept4  *ebpf.Program `ebpf:"handle_sys_exit_accept4"`
	HandleSysExitConnect  *ebpf.Program `ebpf:"handle_sys_exit_connect"`
}

func (p *netPrograms) Close() error {
	return _NetClose(
		p.HandleSysEnterAccept,
		p.HandleSysEnterAccept4,
		p.HandleSysEnterConnect,
		p.HandleSysExitAccept,
		p.HandleSysExitAccept4,
		p.HandleSysExitConnect,
	)
}

func _NetClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed net_bpfeb.o
var _NetBytes []byte
