# ========================= Values.yml ==================================================
#
# This file contains process image names, command line signatures, file names or registry
# keys that are utilized in filter group files to make them more readable and avoid cluttering
# with massive payloads.
#
processes:
  comm:
    svchost:
      - C:\\Windows\\system32\\svchost.exe -k appmodel -s StateRepository
      - C:\\Windows\\system32\\svchost.exe -k appmodel -p -s camsvc
      - C:\\Windows\\system32\\svchost.exe -k appmodel
      - C:\\Windows\\system32\\svchost.exe -k appmodel -p -s tiledatamodelsvc
      - C:\\Windows\\system32\\svchost.exe -k camera -s FrameServer
      - C:\\Windows\\system32\\svchost.exe -k dcomlaunch -s LSM
      - C:\\Windows\\system32\\svchost.exe -k dcomlaunch -s PlugPlay
      # Windows defragmentation
      - C:\\Windows\\system32\\svchost.exe -k defragsvc
      - C:\\Windows\\system32\\svchost.exe -k devicesflow -s DevicesFlowUserSvc
      # Microsoft: The Windows Image Acquisition Service
      - C:\\Windows\\system32\\svchost.exe -k imgsvc
      - C:\\Windows\\system32\\svchost.exe -k localService -s EventSystem
      - C:\\Windows\\system32\\svchost.exe -k localService -s bthserv
      - C:\\Windows\\system32\\svchost.exe -k LocalService -p -s BthAvctpSvc
      - C:\\Windows\\system32\\svchost.exe -k localService -s nsi
      - C:\\Windows\\system32\\svchost.exe -k localService -s w32Time
      # Windows: Network services
      - C:\\Windows\\system32\\svchost.exe -k localServiceAndNoImpersonation
      - C:\\Windows\\system32\\svchost.exe -k localServiceNetworkRestricted -s Dhcp
      - C:\\Windows\\system32\\svchost.exe -k localServiceNetworkRestricted -s EventLog
      - C:\\Windows\\system32\\svchost.exe -k localServiceNetworkRestricted -s TimeBrokerSvc
      - C:\\Windows\\system32\\svchost.exe -k localServiceNetworkRestricted -s WFDSConMgrSvc
      - C:\\Windows\\system32\\svchost.exe -k LocalServiceNetworkRestricted -s BTAGService
      # Win10:1903: Network Connection Broker
      - C:\\Windows\\System32\\svchost.exe -k LocalSystemNetworkRestricted -p -s NcbService
      - C:\\Windows\\system32\\svchost.exe -k localServiceNetworkRestricted
      - C:\\Windows\\system32\\svchost.exe -k localServiceAndNoImpersonation -s SensrSvc
      # Windows: SSDP [ https://en.wikipedia.org/wiki/Simple_Service_Discovery_Protocol ]
      - C:\\Windows\\system32\\svchost.exe -k localServiceAndNoImpersonation -p -s SSDPSRV
      - C:\\Windows\\system32\\svchost.exe -k localServiceNoNetwork
      - C:\\Windows\\system32\\svchost.exe -k localSystemNetworkRestricted -p -s WPDBusEnum
      - C:\\Windows\\system32\\svchost.exe -k localSystemNetworkRestricted -p -s fhsvc
      - C:\\Windows\\system32\\svchost.exe -k localSystemNetworkRestricted -s DeviceAssociationService
      - C:\\Windows\\system32\\svchost.exe -k localSystemNetworkRestricted -s NcbService
      - C:\\Windows\\system32\\svchost.exe -k localSystemNetworkRestricted -s SensorService
      - C:\\Windows\\system32\\svchost.exe -k localSystemNetworkRestricted -s TabletInputService
      - C:\\Windows\\system32\\svchost.exe -k localSystemNetworkRestricted -s UmRdpService
      - C:\\Windows\\system32\\svchost.exe -k localSystemNetworkRestricted -s WPDBusEnum
      # Microsoft: Passport
      - C:\\Windows\\system32\\svchost.exe -k localSystemNetworkRestricted -p -s NgcSvc
      # Microsoft: Passport Container
      - C:\\Windows\\system32\\svchost.exe -k localServiceNetworkRestricted -p -s NgcCtnrSvc